# Episode URLs
EPISODE_URLS = https://chosendl.noxsolutions.com/thechosen/hls/episodes/s01e01/s01e01-en-1080p.m3u8 \
https://chosendl.noxsolutions.com/thechosen/hls/episodes/s01e02/s01e02-en-1080p.m3u8 \
https://chosendl.noxsolutions.com/thechosen/hls/episodes/s01e03/s01e03-en-1080p.m3u8 \
https://chosendl.noxsolutions.com/thechosen/hls/episodes/s01e04/s01e04-en-1080p.m3u8 \
https://chosendl.noxsolutions.com/thechosen/hls/episodes/s01e05/s01e05-en-1080p.m3u8 \
https://chosendl.noxsolutions.com/thechosen/hls/episodes/s01e06/s01e06-en-1080p.m3u8 \
https://chosendl.noxsolutions.com/thechosen/hls/episodes/s01e07/s01e07-en-1080p.m3u8 \
https://chosendl.noxsolutions.com/thechosen/hls/episodes/s01e08/s01e08-en-1080p.m3u8

# Episode titles
EPISODE_TITLES = [S1E1]_I_Have_Called_You_By_Name \
[S1E2]_Shabbat \
[S1E3]_Jesus_Loves_The_Little_Children \
[S1E4]_The_Rock_On_Which_It_Is_Built \
[S1E5]_The_Wedding_Gift \
[S1E6]_Indescribable_Compassion \
[S1E7]_Invitations \
[S1E8]_I_Am_He \

# Episode format
FORMAT = bestvideo+program_audio-English

include ../common.mk