# Episode URLs
EPISODE_URLS = https://chosendl.noxsolutions.com/thechosen/hls/episodes/s02e01/s02e01-en-1080p.m3u8 \
https://chosendl.noxsolutions.com/thechosen/hls/episodes/s02e02/s02e02-en-1080p.m3u8 \
https://chosendl.noxsolutions.com/thechosen/hls/episodes/s02e03/s02e03-en-1080p.m3u8 \
https://chosendl.noxsolutions.com/thechosen/hls/episodes/s02e04/s02e04-en-1080p.m3u8 \
https://chosendl.noxsolutions.com/thechosen/hls/episodes/s02e05/s02e05-en-1080p.m3u8 \
https://chosendl.noxsolutions.com/thechosen/hls/episodes/s02e06/s02e06-en-1080p.m3u8 \
https://chosendl.noxsolutions.com/thechosen/hls/episodes/s02e07/s02e07-en-1080p.m3u8 \
https://chosendl.noxsolutions.com/thechosen/hls/episodes/s02e08/s02e08-en-1080p.m3u8

# Episode titles
EPISODE_TITLES = [S2E1]_Thunder \
[S2E2]_I_Saw_You \
[S2E3]_Matthew_4_24 \
[S2E4]_The_Perfect_Opportunity \
[S2E5]_Spirit \
[S2E6]_Unlawful \
[S2E7]_Reckoning \
[S2E8]_Beyond_Mountains \

include ../common.mk