# Episode URLs
EPISODE_URLS = https://chosendl.noxsolutions.com/thechosen/hls/episodes/s03e01-yewg652h-captions/s03e01-en-1080p.m3u8 \
https://chosendl.noxsolutions.com/thechosen/hls/episodes/s03e02-eyag62g5-captions/s03e02_episode_eng_1080p.m3u8 \
https://chosendl.noxsolutions.com/thechosen/hls/episodes/s03e03-fewyqw6ef-captions/s03e03_episode_eng_1080p.m3u8 \
https://chosendl.noxsolutions.com/thechosen/hls/episodes/s03e04-fdsay7a6hw-captions/s03e04_episode_eng_1080p.m3u8 \
https://chosendl.noxsolutions.com/thechosen/hls/episodes/s03e05-ausk126fs-captions/s03e05_episode_eng_1080p.m3u8 \
https://chosendl.noxsolutions.com/hls/s03e06_episode_eng_1080p_sefv7jc8/s03e06_episode_eng_1080p_sefv7jc8.m3u8 \
https://chosendl.noxsolutions.com/hls/s03e07_episode_eng_1080p_c2n42k83/s03e07_episode_eng_1080p_c2n42k83.m3u8 \
https://chosendl.noxsolutions.com/hls/s03e08_episode_eng_1080p_gyg0jib8/s03e08_episode_eng_1080p_gyg0jib8.m3u8

# Episode titles
EPISODE_TITLES = [S3E1]_Homecoming \
[S3E2]_Two_by_Two \
[S3E3]_Physician_Heal_Thyself \
[S3E4]_Clean_Part_1 \
[S3E5]_Clean_Part_2 \
[S3E6]_Intensity_in_Tent_City \
[S3E7]_Ears_to_Hear \
[S3E8]_Sustenance \

# Episode format
FORMAT = 8850

include ../common.mk